from __future__ import annotations

from typing import Dict

import numpy as np
import plotly.graph_objects as go
import streamlit as st

from components.data_access import get_dataset, get_metadata
from components.filters import sidebar_filters
from components.layout import inject_css, phase_callout
from components.plot_helpers import plotly_with_export
from utils import build_metadata_frame, compute_spacing_ratios, format_float

 
def _overview_metrics(filtered_df, selection) -> None:
    col1, col2, col3 = st.columns(3)
    col1.metric("Datasets", len(filtered_df))
    col2.metric("Distinct λ", len(filtered_df["lam"].unique()))
    col3.metric("Boundary conditions", ", ".join(sorted(set(filtered_df["bc"].unique()))))
    if selection["lam"]:
        st.caption("λ filters: " + ", ".join(format_float(float(val)) for val in selection["lam"]))


def _quick_plots(dataset: Dict, label: str) -> None:
    eigvals = np.asarray(dataset.get("E", []))
    ipr = np.asarray(dataset.get("IPRs", []))
    mean_r = float(dataset.get("mean_r", np.nan))

    with st.expander("Quick spectral snapshot", expanded=True):
        if eigvals.size:
            fig = go.Figure()
            fig.add_trace(
                go.Scatter(
                    x=np.arange(eigvals.size),
                    y=eigvals,
                    mode="lines+markers",
                    marker=dict(size=4),
                    line=dict(width=1.2),
                )
            )
            fig.update_layout(
                title=f"Eigenvalue spectrum — {label}",
                xaxis_title="Index n",
                yaxis_title="E_n",
                template="plotly_dark",
            )
            plotly_with_export(fig, filename="eigenvalues_overview")
        else:
            st.warning("Eigenvalues missing in this dataset.")

        if np.isfinite(mean_r):
            phase_callout(mean_r)

    if ipr.size:
        with st.expander("Inverse participation ratio", expanded=False):
            fig = go.Figure()
            fig.add_trace(go.Bar(x=np.arange(ipr.size), y=ipr))
            fig.update_layout(
                xaxis_title="Eigenstate index",
                yaxis_title="IPR",
                template="plotly_dark",
            )
            plotly_with_export(fig, filename="ipr_overview")

    ratios = compute_spacing_ratios(eigvals)
    if ratios.size:
        with st.expander("Level-spacing ratios", expanded=False):
            fig = go.Figure()
            fig.add_trace(go.Histogram(x=ratios, nbinsx=40))
            fig.update_layout(
                xaxis_title="Spacing ratio r",
                yaxis_title="Count",
                template="plotly_dark",
            )
            plotly_with_export(fig, filename="spacing_ratio_hist")
    elif eigvals.size:
        st.info("Need more eigenvalues to form spacing statistics.")


def main() -> None:
    st.set_page_config(page_title="GAAH Research Dashboard", layout="wide")
    inject_css()
    st.title("GAAH Research Dashboard")
    st.caption(
        "Interactive analysis of spectral statistics and dynamics for the generalized Aubry–André–Harper model."
    )

    metadata = get_metadata()
    if not metadata:
        st.info("No simulation outputs found in `data/`. Add `.npz` files generated by the pipeline.")
        return

    meta_df = build_metadata_frame(metadata)
    filters = sidebar_filters(meta_df)
    filtered_df = filters["filtered"]
    selection = filters["selection"]

    _overview_metrics(filtered_df, selection)

    if filters["dataset_path"] is None:
        st.warning("Select a dataset from the sidebar to view previews.")
        st.dataframe(filtered_df.reset_index(drop=True))
        return

    dataset_path = filters["dataset_path"]
    dataset = get_dataset(dataset_path)
    label = meta_df.set_index("path").loc[dataset_path, "label"]

    _quick_plots(dataset, label)

    st.subheader("Filtered metadata")
    st.dataframe(filtered_df.reset_index(drop=True))


if __name__ == "__main__":
    main()
